name: scotty-friend-list-server
version: 0.1.0.0
github: 'zkourouma/scotty-friend-list-server'
license: BSD3
author: 'Zack Kourouma'
maintainer: 'zack@kourouma.me'
copyright: '2019 Zack Kourouma'

ghc-options:
- -Wall
- -threaded
- -O2
- -rtsopts
- -with-rtsopts=-N

dependencies:
- base >=4.7 && <5
- aeson
- bytestring
- text

other-modules:
  - Paths_scotty_friend_list_server

library:
  source-dirs: src

executables:
  server:
    main: Main.hs
    source-dirs: app
    dependencies:
      - scotty
      - scotty-friend-list-server

data-files:
  - data/*
